name: Feature Branch Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        -   name: Checkout code
            uses: actions/checkout@v2
        -   name: Build and test
            run: |
                chmod +x ./test-workflow/build/build.sh
                ./test-workflow/build/build.sh